% Combine two profiles data files into pobs
function DeblurToGap2(left_photo_filepath,right_photo_filepath)

left_photo_name = '1';
right_photo_name = '2';
measurement_sd_x = 0.5;
measurement_sd_y = 0.5;
% left_photo_filepath = 'DSC_0013.JPG_points.csv';
% right_photo_filepath = 'DSC_0009.JPG_points.csv';
output_filename = 'pobsP.txt';

left_data_fid = fopen(left_photo_filepath,'rt');
left_data_read = textscan(left_data_fid,'%s %s %f %f %f %f %*[^\n]', ...
    'Delimiter',',', ...
    'HeaderLines',3);
fclose(left_data_fid);

right_data_fid = fopen(right_photo_filepath,'rt');
right_data_read = textscan(right_data_fid,'%s %s %f %f %f %f %*[^\n]', ...
    'Delimiter',',', ...
    'HeaderLines',3);
fclose(right_data_fid);

number_of_obs_sets = length(right_data_read{1});

obsfile_fid = fopen(output_filename,'wt');
fprintf(obsfile_fid, '#  Photo observation file from measured blurs.\n');
fprintf(obsfile_fid, '#\n');
fprintf(obsfile_fid, '#  BlurToGap program run %s.\n',datestr(now));
fprintf(obsfile_fid, '#\n');
fprintf(obsfile_fid, '#  Input files:\n');
fprintf(obsfile_fid, '#  Left pobs data   :  %s\n',left_photo_filepath);
fprintf(obsfile_fid, '#  Rght pobs data   :  %s\n',right_photo_filepath);
fprintf(obsfile_fid, '#\n');
fprintf(obsfile_fid, '#  Output file:\n');
fprintf(obsfile_fid, '#  pobs file        :  %s\n',output_filename);
fprintf(obsfile_fid, '#  Units are originally in pixels\n');
fprintf(obsfile_fid, '#\n');
fprintf(obsfile_fid, '#\n');
fprintf(obsfile_fid, '# Phot ID\tPt ID\tX\tY\tStdDev X\tStdDev Y\n');
fprintf(obsfile_fid, '#\n');

for obs_row = 1:number_of_obs_sets
    % First way round
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        left_photo_name, ...
        strcat(left_data_read{1}{obs_row},'_A1'), ...
        left_data_read{3}(obs_row), ...
        left_data_read{4}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        right_photo_name, ...
        strcat(right_data_read{1}{obs_row},'_A1'), ...
        right_data_read{3}(obs_row), ...
        right_data_read{4}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        left_photo_name, ...
        strcat(left_data_read{1}{obs_row},'_A2'), ...
        left_data_read{5}(obs_row), ...
        left_data_read{6}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        right_photo_name, ...
        strcat(right_data_read{1}{obs_row},'_A2'), ...
        right_data_read{5}(obs_row), ...
        right_data_read{6}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    
    
    
    % Other way round
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        left_photo_name, ...
        strcat(left_data_read{1}{obs_row},'_B1'), ...
        left_data_read{3}(obs_row), ...
        left_data_read{4}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        right_photo_name, ...
        strcat(right_data_read{1}{obs_row},'_B1'), ...
        right_data_read{5}(obs_row), ...
        right_data_read{6}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        left_photo_name, ...
        strcat(left_data_read{1}{obs_row},'_B2'), ...
        left_data_read{5}(obs_row), ...
        left_data_read{6}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    fprintf(obsfile_fid,'%s\t%s\t%4.2f\t%4.2f\t%g\t%g\n',...
        right_photo_name, ...
        strcat(right_data_read{1}{obs_row},'_B2'), ...
        right_data_read{3}(obs_row), ...
        right_data_read{4}(obs_row), ...
        measurement_sd_x, ...
        measurement_sd_y);
    
    
end

fclose(obsfile_fid);