function [stringout] = remove_option_from_string(stringin)

scanned = textscan(stringin,'%s %s %s %s %s %s %s', ...
    'Delimiter', '\t');

newname = [ scanned{1}{1}(1:end-2)  scanned{1}{1}(end) ];

stringout = sprintf( '%s\t%s\t%s\t%s\t%s\t%s\t%s', ...
     newname, ...
 scanned{2}{1}, ...
 scanned{3}{1}, ...
 scanned{4}{1}, ...
 scanned{5}{1}, ...
 scanned{6}{1}, ...
 scanned{7}{1});